import { writeFileSync, mkdirSync } from 'fs';
import { resolveDark, resolveLight } from '../themes/palette';
import tokens from '../tokens.json';
import pkg from '../package.json';

const DEFAULT_ACCENT = 'violet' as const;

const output = {
  meta: {
    version:      pkg.version,
    defaultAccent: DEFAULT_ACCENT,
    generated:    new Date().toISOString(),
    description:  'Resolved Fujin design tokens. Generated by `npm run export-tokens`. Do not edit by hand.',
  },
  tokens: {
    fontFamily:     tokens.typography.fontFamily.base,
    fontFamilyMono: tokens.typography.fontFamily.mono,
  },
  dark:  resolveDark(DEFAULT_ACCENT),
  light: resolveLight(DEFAULT_ACCENT),
};

mkdirSync('dist', { recursive: true });
writeFileSync('dist/tokens-resolved.json', JSON.stringify(output, null, 2) + '\n');
console.log(`tokens-resolved.json written (v${pkg.version}, accent: ${DEFAULT_ACCENT})`);
