// Custom Style Dictionary formats for Fujin.
//
// Why custom formats rather than the built-ins: Fujin's CSS custom-property
// contract (`--fujin-bg-base`, `--fujin-text-primary`, …) predates this pipeline
// and is already consumed byname in downstream repositories. Style Dictionary's
// stock `css/variables` format derives variable names from the full token path,
// which would rename every variable (`--fujin-semantic-dark-bg-base`) and break
// those consumers. So we let Style Dictionary do what only it can do — parse
// DTCG, resolve `{alias.references}`, validate the graph — and keep full control
// of the emitted names here.
//
// Three build targets, one shared value model:
//   fujin/css          -> dist/tokens.css          (CSS custom properties)
//   fujin/js           -> dist/tokens.js           (ESM token module)
//   fujin/dts          -> dist/tokens.d.ts         (types for the above)
//   fujin/mantine      -> dist/mantine-theme.js    (Mantine theme object factory)
//   fujin/mantine-dts  -> dist/mantine-theme.d.ts
//   fujin/resolved     -> dist/tokens-resolved.json (legacy artifact, see below)

import { readFileSync } from 'node:fs';

// Repo-level metadata (accent list, default accent, version namespaces) lives in
// tokens.json's root `$extensions`. It is metadata *about* the token file rather
// than a token, and Style Dictionary drops root-level `$`-prefixed keys from the
// per-platform dictionary it hands to a format — so read it from source instead
// of from `dictionary.tokens`.
const SOURCE = JSON.parse(readFileSync(new URL('../tokens.json', import.meta.url), 'utf8'));
const EXT = SOURCE.$extensions?.['dev.starlightdaemon.fujin'] ?? {};

const BANNER = (file) =>
  `/**\n` +
  ` * ${file}\n` +
  ` *\n` +
  ` * GENERATED FILE — DO NOT EDIT.\n` +
  ` * Source of truth: tokens.json (DTCG). Regenerate with \`npm run build\`.\n` +
  ` * Edits here are lost on the next build and will silently diverge from the\n` +
  ` * token source, which is the exact failure mode CONSUMERS.md exists to prevent.\n` +
  ` */\n`;

const JSON_BANNER_NOTE =
  'Resolved Fujin design tokens. Generated by `npm run build`. Do not edit by hand.';

// ---------------------------------------------------------------------------
// Value coercion
// ---------------------------------------------------------------------------

/**
 * DTCG `dimension` values are authored as unit-bearing strings. Two consumers
 * want two different things out of them:
 *   - CSS wants the string verbatim (`16px`, `0.05em`).
 *   - React inline styles and React Native want bare numbers — but only for px,
 *     because `em` has no meaning in RN and web CSS needs the unit preserved.
 * So: px dimensions become numbers in the JS module, everything else stays a
 * string. This reproduces the pre-pipeline token contract exactly.
 */
function jsValue(token) {
  const v = token.$value;
  if (token.$type === 'dimension' && typeof v === 'string' && v.endsWith('px')) {
    return Number.parseFloat(v);
  }
  if (token.$type === 'shadow') return shadowToCss(v);
  return v;
}

function cssValue(token) {
  if (token.$type === 'shadow') return shadowToCss(token.$value);
  return String(token.$value);
}

/** DTCG shadow object -> CSS box-shadow string, omitting zero offsets/spread. */
function shadowToCss(v) {
  const list = Array.isArray(v) ? v : [v];
  return list
    .map((s) => {
      const parts = [trimZero(s.offsetX), trimZero(s.offsetY), trimZero(s.blur)];
      if (s.spread && Number.parseFloat(s.spread) !== 0) parts.push(trimZero(s.spread));
      parts.push(s.color);
      return parts.join(' ');
    })
    .join(', ');
}

/** `0px` -> `0`; anything else unchanged. Matches the hand-authored CSS it replaces. */
const trimZero = (s) => (Number.parseFloat(s) === 0 ? '0' : s);

const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// ---------------------------------------------------------------------------
// Model — walk the resolved DTCG tree once, produce everything else from it
// ---------------------------------------------------------------------------

const isToken = (n) => n !== null && typeof n === 'object' && '$value' in n;

function walk(node, path, visit) {
  if (isToken(node)) return visit(node, path);
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    walk(child, [...path, key], visit);
  }
}

/**
 * CSS custom-property name for a non-semantic (scalar) token path.
 * Explicit rules, not a generic join — the names are a public contract.
 */
function scalarCssName(path) {
  const p = path.join('.');
  if (p === 'spacing.base') return 'spacing-base';
  if (path[0] === 'spacing' && path[1] === 'scale') return `spacing-${path[2]}`;
  if (path[0] === 'radius') return `radius-${path[1]}`;
  if (path[0] === 'typography') {
    const kind = {
      fontFamily: 'font-family',
      fontSize: 'font-size',
      fontWeight: 'font-weight',
      lineHeight: 'line-height',
      letterSpacing: 'letter-spacing',
    }[path[1]];
    return kind ? `${kind}-${path[2]}` : null;
  }
  if (path[0] === 'opacity') return `opacity-${path[1]}`;
  if (path[0] === 'border' && path[1] === 'width') return `border-width-${path[2]}`;
  if (path[0] === 'layout') return `layout-${path[1]}`;
  if (path[0] === 'breakpoints') return `breakpoint-${path[1]}`;
  if (path[0] === 'transition' && path[1] === 'duration') return `duration-${path[2]}`;
  if (path[0] === 'transition' && path[1] === 'easing') return `easing-${kebab(path[2])}`;
  return null;
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** Build the single shared model every format below renders from. */
export function buildModel(dictionary) {
  const t = dictionary.tokens;
  const ext = EXT;

  // --- primitive palette: hue -> 10-tuple (plus the `common` singletons) ---
  const palette = {};
  const common = {};
  for (const [hue, ramp] of Object.entries(t.color.palette)) {
    if (hue.startsWith('$')) continue;
    if (hue === 'common') {
      for (const [k, tok] of Object.entries(ramp)) {
        if (!k.startsWith('$')) common[k] = tok.$value;
      }
      continue;
    }
    palette[hue] = Array.from({ length: 10 }, (_, i) => ramp[String(i)].$value);
  }

  // --- semantic roles per mode: `--fujin-<role>` -> resolved value ---
  const semantic = {};
  // Which semantic roles are accent-derived, and at which shade index. Read out
  // of the *unresolved* alias so the mapping stays data-driven: if someone
  // repoints interactive.hover at shade 5, this follows without a code change.
  const accentShades = {};
  for (const mode of ['dark', 'light']) {
    const vars = {};
    walk(t.semantic[mode], [], (token, path) => {
      const name = `--fujin-${path.join('-')}`;
      vars[name] = cssValue(token);
      const ref = token.original?.$value;
      if (typeof ref === 'string') {
        const m = /^\{color\.palette\.([a-z]+)\.(\d)\}$/.exec(ref);
        if (m && m[1] === ext.defaultAccent) accentShades[name] = Number(m[2]);
      }
    });
    semantic[mode] = vars;
  }

  // --- scalars: nested JS model + flat CSS map, from one walk ---
  const scalars = {};
  const scalarCss = {};
  for (const group of ['spacing', 'radius', 'typography', 'opacity', 'border', 'layout', 'breakpoints', 'transition']) {
    walk(t[group], [group], (token, path) => {
      // nested JS shape, camelCasing any hyphenated leaf key
      let cursor = scalars;
      for (const seg of path.slice(0, -1)) cursor = cursor[seg] ??= {};
      cursor[camel(path.at(-1))] = jsValue(token);

      const cssName = scalarCssName(path);
      if (cssName) scalarCss[`--fujin-${cssName}`] = cssValue(token);
    });
  }

  return {
    ext,
    palette,
    common,
    semantic,
    accentShades,
    scalars,
    scalarCss,
    accentOptions: ext.accentOptions ?? [],
    defaultAccent: ext.defaultAccent ?? 'violet',
  };
}

/** Semantic vars for a given mode + accent, applying the accent-shade overrides. */
export function resolveForAccent(model, mode, accent) {
  const ramp = model.palette[accent];
  const out = { ...model.semantic[mode] };
  for (const [name, shade] of Object.entries(model.accentShades)) {
    out[name] = ramp[shade];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Format: CSS custom properties
// ---------------------------------------------------------------------------

const cssBlock = (selector, entries, indent = '  ') =>
  `${selector} {\n` +
  Object.entries(entries).map(([k, v]) => `${indent}${k}: ${v};`).join('\n') +
  `\n}\n`;

export const cssFormat = {
  name: 'fujin/css',
  format({ dictionary }) {
    const m = buildModel(dictionary);

    const paletteVars = {};
    for (const [hue, ramp] of Object.entries(m.palette)) {
      ramp.forEach((v, i) => { paletteVars[`--fujin-palette-${hue}-${i}`] = v; });
    }
    for (const [k, v] of Object.entries(m.common)) {
      paletteVars[`--fujin-palette-common-${k}`] = v;
    }

    const out = [];
    out.push(BANNER('tokens.css').replace(/^\/\*\*/, '/*'));
    out.push(
      `/* Dark is the default mode. Apply light by setting [data-fujin-mode="light"]\n` +
      `   or the .fujin-light class on <html> or any container element.\n` +
      `   Apply a non-default accent with [data-fujin-accent="<name>"] or\n` +
      `   .fujin-accent-<name>. Accents override only the --fujin-interactive-* roles. */\n`
    );

    out.push('/* --- primitive palette (reference only; prefer the semantic roles) --- */');
    out.push(cssBlock(':root', paletteVars));

    out.push('/* --- scale tokens (mode-invariant) --- */');
    out.push(cssBlock(':root', m.scalarCss));

    out.push('/* --- semantic roles: dark (default) --- */');
    out.push(cssBlock(':root, [data-fujin-mode="dark"], .fujin-dark', m.semantic.dark));

    out.push('/* --- semantic roles: light --- */');
    out.push(cssBlock('[data-fujin-mode="light"], .fujin-light', m.semantic.light));

    out.push('/* --- accent presets (override the interactive roles only) --- */');
    for (const accent of m.accentOptions) {
      if (accent === m.defaultAccent) continue;
      const ramp = m.palette[accent];
      const overrides = {};
      for (const [name, shade] of Object.entries(m.accentShades)) overrides[name] = ramp[shade];
      out.push(cssBlock(`[data-fujin-accent="${accent}"], .fujin-accent-${accent}`, overrides));
    }

    return out.join('\n');
  },
};

// ---------------------------------------------------------------------------
// Format: ESM token module
// ---------------------------------------------------------------------------

const lit = (v) => JSON.stringify(v);

export const jsFormat = {
  name: 'fujin/js',
  format({ dictionary }) {
    const m = buildModel(dictionary);

    const paletteSrc = Object.entries(m.palette)
      .map(([hue, ramp]) => `  ${hue}: ${lit(ramp)},`)
      .join('\n');

    const accentShadeSrc = Object.entries(m.accentShades)
      .map(([name, shade]) => `  ${lit(name)}: ${shade},`)
      .join('\n');

    const modeSrc = (mode) =>
      Object.entries(m.semantic[mode])
        .map(([k, v]) => `  ${lit(k)}: ${lit(v)},`)
        .join('\n');

    return `${BANNER('tokens.js')}
/** Primitive palette. Hues red…orange are Open Color; \`dark\` is Mantine's dark ramp. */
export const palette = Object.freeze({
${paletteSrc}
});

/** Palette entries that are not part of a 10-step ramp. */
export const commonColors = Object.freeze(${lit(m.common)});

/** Accent presets Fujin ships a theme for. */
export const accentOptions = Object.freeze(${lit(m.accentOptions)});

/** Accent applied when a caller does not choose one. */
export const defaultAccent = ${lit(m.defaultAccent)};

/**
 * Scale tokens — mode- and accent-invariant. px dimensions are numbers (React
 * inline styles and React Native both want numbers); em dimensions stay strings.
 */
export const tokens = Object.freeze(${JSON.stringify(m.scalars, null, 2)});

/**
 * Mode- and accent-invariant \`--fujin-*\` custom properties (spacing, radius,
 * type scale, opacity, borders, breakpoints, transitions). Separate from the
 * semantic maps because these never change with mode or accent — inject them
 * once. FujinThemeProvider spreads this alongside the mode map so that
 * \`var(--fujin-spacing-md)\` resolves for component consumers who never load
 * tokens.css.
 */
export const scalarVars = Object.freeze(${JSON.stringify(m.scalarCss, null, 2)});

/** Which semantic roles track the accent, and at which shade index. */
const ACCENT_SHADES = Object.freeze({
${accentShadeSrc}
});

const SEMANTIC_DARK = Object.freeze({
${modeSrc('dark')}
});

const SEMANTIC_LIGHT = Object.freeze({
${modeSrc('light')}
});

function withAccent(base, accent) {
  const ramp = palette[accent];
  if (!ramp) throw new Error(\`Unknown Fujin accent: \${accent}\`);
  const out = { ...base };
  for (const name of Object.keys(ACCENT_SHADES)) out[name] = ramp[ACCENT_SHADES[name]];
  return out;
}

/** Dark-mode \`--fujin-*\` custom properties for the given accent. */
export function resolveDark(accent = defaultAccent) {
  return withAccent(SEMANTIC_DARK, accent);
}

/** Light-mode \`--fujin-*\` custom properties for the given accent. */
export function resolveLight(accent = defaultAccent) {
  return withAccent(SEMANTIC_LIGHT, accent);
}

/** Both modes at once, for callers that inject a full stylesheet. */
export function resolveAll(accent = defaultAccent) {
  return { dark: resolveDark(accent), light: resolveLight(accent) };
}

export default tokens;
`;
  },
};

// ---------------------------------------------------------------------------
// Format: .d.ts for the token module
// ---------------------------------------------------------------------------

/** Emit a structural type literal for a plain nested value object. */
function typeLiteral(obj, indent = '  ') {
  const lines = Object.entries(obj).map(([k, v]) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : lit(k);
    if (v !== null && typeof v === 'object') {
      return `${indent}readonly ${key}: {\n${typeLiteral(v, indent + '  ')}\n${indent}};`;
    }
    return `${indent}readonly ${key}: ${typeof v === 'number' ? v : lit(v)};`;
  });
  return lines.join('\n');
}

export const dtsFormat = {
  name: 'fujin/dts',
  format({ dictionary }) {
    const m = buildModel(dictionary);
    const hues = Object.keys(m.palette).map(lit).join(' | ');
    const accents = m.accentOptions.map(lit).join(' | ');

    return `${BANNER('tokens.d.ts')}
/** Every hue in the primitive palette. Matches the pre-pipeline \`MantineAccentKey\`. */
export type MantineAccentKey = ${hues};

/** The subset of hues Fujin ships as a selectable accent preset. */
export type FujinAccent = ${accents};

export type ColorRamp = readonly [
  string, string, string, string, string, string, string, string, string, string
];

export declare const palette: Readonly<Record<MantineAccentKey, ColorRamp>>;
export declare const commonColors: Readonly<{ white: string; black: string }>;
export declare const accentOptions: readonly FujinAccent[];
export declare const defaultAccent: FujinAccent;

export declare const tokens: {
${typeLiteral(m.scalars)}
};

/** Map of \`--fujin-*\` custom-property name to resolved value. */
export type FujinCssVars = Record<string, string>;

/** Mode- and accent-invariant \`--fujin-*\` custom properties. */
export declare const scalarVars: FujinCssVars;

export declare function resolveDark(accent?: MantineAccentKey): FujinCssVars;
export declare function resolveLight(accent?: MantineAccentKey): FujinCssVars;
export declare function resolveAll(accent?: MantineAccentKey): {
  dark: FujinCssVars;
  light: FujinCssVars;
};

export default tokens;
`;
  },
};

// ---------------------------------------------------------------------------
// Format: Mantine theme object
// ---------------------------------------------------------------------------

/**
 * Mantine components whose border-radius is hardcoded in @mantine/core's
 * stylesheet rather than derived from `--mantine-radius-default`. Setting
 * `defaultRadius: 0` on the theme does NOT reach them — each one has its own
 * `--<component>-radius` defaulting to a fully-round 62.5rem/1000rem/50%.
 * Without the per-component defaultProps below, a Fujin-themed app silently
 * renders pill-shaped Badges and circular Avatars inside a system whose
 * canonical radius is 0. Verified against @mantine/core 7.x styles.css.
 */
const ROUNDED_BY_DEFAULT = [
  'Avatar',
  'Badge',
  'Chip',
  'ColorSwatch',
  'Indicator',
  'Pill',
  'RangeSlider',
  'Slider',
  'Stepper',
  'Switch',
  'Timeline',
];

export const mantineFormat = {
  name: 'fujin/mantine',
  format({ dictionary }) {
    const m = buildModel(dictionary);
    const s = m.scalars;

    const px = (n) => `${n}px`;
    const fs = s.typography.fontSize;
    const sp = s.spacing.scale;

    const fontSizes = { xs: px(fs.xs), sm: px(fs.sm), md: px(fs.md), lg: px(fs.lg), xl: px(fs.xl) };
    const spacing = {
      xxs: px(sp.xxs), xs: px(sp.xs), sm: px(sp.sm), md: px(sp.md),
      lg: px(sp.lg), xl: px(sp.xl), xxl: px(sp.xxl),
    };
    const radius = { xs: px(s.radius.xs), sm: px(s.radius.sm), md: px(s.radius.md), lg: px(s.radius.lg), xl: px(s.radius.xl) };

    // Mantine keys line heights xs..xl; Fujin names them by intent. Documented
    // mapping rather than an invented scale: small text is tight, body is base,
    // display text is relaxed.
    const lh = s.typography.lineHeight;
    const lineHeights = { xs: String(lh.tight), sm: String(lh.tight), md: String(lh.base), lg: String(lh.base), xl: String(lh.relaxed) };

    // Mantine v7 expects breakpoints in em. Fujin authors them in px; /16 is the
    // standard root-font-size conversion and reproduces Mantine's own defaults.
    const bp = s.breakpoints;
    const breakpoints = Object.fromEntries(Object.entries(bp).map(([k, v]) => [k, `${v / 16}em`]));

    // Mantine has no per-color-scheme shadow scale. Fujin is dark-first, so the
    // dark shadow set is what the Mantine theme carries; the light values remain
    // available as --fujin-shadow-* for anything that needs them.
    const shadows = Object.fromEntries(
      ['xs', 'sm', 'md', 'lg', 'xl'].map((k) => [k, m.semantic.dark[`--fujin-shadow-${k}`]])
    );

    const components = Object.fromEntries(
      ROUNDED_BY_DEFAULT.map((c) => [c, { defaultProps: { radius: 0 } }])
    );

    return `${BANNER('mantine-theme.js')}
/**
 * Mantine theme object built from tokens.json. Deliberately imports nothing from
 * @mantine/core — @mantine/core is an optional peer dependency, so this module
 * must be loadable by a native-only or CSS-only consumer. Pass the result
 * straight to \`<MantineProvider theme={...}>\`; it satisfies MantineThemeOverride
 * structurally.
 */

import { palette, defaultAccent } from './tokens.js';

/**
 * Mantine components whose radius is hardcoded in @mantine/core's stylesheet and
 * therefore NOT covered by \`defaultRadius\`. Each defaults to a fully-round
 * value; without the defaultProps below, a Fujin-themed app renders pill-shaped
 * Badges and circular Avatars inside a canonical zero-radius system.
 */
export const roundedByDefault = Object.freeze(${lit(ROUNDED_BY_DEFAULT)});

const BASE = Object.freeze({
  fontFamily: ${lit(s.typography.fontFamily.base)},
  fontFamilyMonospace: ${lit(s.typography.fontFamily.mono)},
  headings: {
    fontFamily: ${lit(s.typography.fontFamily.base)},
    fontWeight: ${lit(String(s.typography.fontWeight.semibold))},
    sizes: {
      h1: { fontSize: ${lit(px(fs.h1))}, lineHeight: ${lit(String(lh.tight))} },
      h2: { fontSize: ${lit(px(fs.h2))}, lineHeight: ${lit(String(lh.tight))} },
      h3: { fontSize: ${lit(px(fs.h3))}, lineHeight: ${lit(String(lh.tight))} },
      h4: { fontSize: ${lit(px(fs.h4))}, lineHeight: ${lit(String(lh.base))} },
      h5: { fontSize: ${lit(px(fs.h5))}, lineHeight: ${lit(String(lh.base))} },
      h6: { fontSize: ${lit(px(fs.h6))}, lineHeight: ${lit(String(lh.base))} },
    },
  },
  fontSizes: ${JSON.stringify(fontSizes, null, 2)},
  spacing: ${JSON.stringify(spacing, null, 2)},
  radius: ${JSON.stringify(radius, null, 2)},
  defaultRadius: ${s.radius.default},
  lineHeights: ${JSON.stringify(lineHeights, null, 2)},
  shadows: ${JSON.stringify(shadows, null, 2)},
  breakpoints: ${JSON.stringify(breakpoints, null, 2)},
  colors: palette,
  primaryShade: { light: 6, dark: 6 },
  components: ${JSON.stringify(components, null, 2)},
});

/**
 * Build the Mantine theme override for one accent.
 *
 * Validated against the full palette rather than \`accentOptions\`: every hue is
 * present in \`theme.colors\`, so every hue is a structurally valid Mantine
 * \`primaryColor\`. \`accentOptions\` is the *curated* set Fujin ships a preset for
 * (see themes/index.ts) — a narrower recommendation, not a runtime constraint.
 */
export function createFujinMantineTheme(accent = defaultAccent) {
  if (!Object.prototype.hasOwnProperty.call(palette, accent)) {
    throw new Error(
      \`Unknown Fujin accent: \${accent}. Expected one of: \${Object.keys(palette).join(', ')}\`
    );
  }
  return { ...BASE, primaryColor: accent };
}

export default createFujinMantineTheme;
`;
  },
};

export const mantineDtsFormat = {
  name: 'fujin/mantine-dts',
  format() {
    return `${BANNER('mantine-theme.d.ts')}
import type { MantineAccentKey } from './tokens';

/**
 * Structural shape of the generated theme. Kept deliberately loose (\`unknown\`
 * leaves are not used) so it assigns cleanly to Mantine's MantineThemeOverride
 * without this package taking a type dependency on @mantine/core.
 */
export interface FujinMantineTheme {
  primaryColor: MantineAccentKey;
  primaryShade: { light: number; dark: number };
  defaultRadius: number;
  fontFamily: string;
  fontFamilyMonospace: string;
  headings: Record<string, unknown>;
  fontSizes: Record<string, string>;
  spacing: Record<string, string>;
  radius: Record<string, string>;
  lineHeights: Record<string, string>;
  shadows: Record<string, string>;
  breakpoints: Record<string, string>;
  colors: Readonly<Record<MantineAccentKey, readonly string[]>>;
  components: Record<string, { defaultProps: { radius: number } }>;
}

/** Mantine components whose radius is hardcoded upstream and needs an explicit 0. */
export declare const roundedByDefault: readonly string[];

export declare function createFujinMantineTheme(accent?: MantineAccentKey): FujinMantineTheme;

export default createFujinMantineTheme;
`;
  },
};

// ---------------------------------------------------------------------------
// Format: legacy resolved-token JSON
// ---------------------------------------------------------------------------

/**
 * dist/tokens-resolved.json predates this pipeline and is read verbatim by
 * audiobookshelf-now-playing (`app/fujin_tokens.py` resolves
 * `../../Fujin/dist/tokens-resolved.json`). Its shape is therefore a
 * compatibility contract, not a design choice — keep `meta` / `tokens` / `dark`
 * / `light` exactly as they were. New keys are additive and safe; removing or
 * renaming one breaks that consumer.
 */
export const resolvedJsonFormat = {
  name: 'fujin/resolved',
  format({ dictionary, options }) {
    const m = buildModel(dictionary);
    return JSON.stringify(
      {
        meta: {
          version: options.version,
          defaultAccent: m.defaultAccent,
          generated: options.generatedAt,
          description: JSON_BANNER_NOTE,
        },
        tokens: {
          fontFamily: m.scalars.typography.fontFamily.base,
          fontFamilyMono: m.scalars.typography.fontFamily.mono,
        },
        dark: resolveForAccent(m, 'dark', m.defaultAccent),
        light: resolveForAccent(m, 'light', m.defaultAccent),
      },
      null,
      2
    ) + '\n';
  },
};

export const formats = [
  cssFormat,
  jsFormat,
  dtsFormat,
  mantineFormat,
  mantineDtsFormat,
  resolvedJsonFormat,
];
